Gygl.WebPage/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Web.Services;

namespace Gygl.WebPage.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Top()
        {
            return PartialView();
        }

        public PartialViewResult Top2()
        {
            return PartialView();
        }

        public PartialViewResult Top3()
        {
            return PartialView();
        }

        public PartialViewResult TopShare() {
            return PartialView();
        }

        public PartialViewResult Bottom()
        {
            return PartialView();
        }

        public PartialViewResult Header()
        {
            return PartialView();
        }

        

        /// <summary>
        /// session不自动关闭
        /// </summary>
        [WebMethod(EnableSession = true)]
        public void PokePage()
        {

        }
    }
}

Gygl.WebPage/Controllers/NewsController.cs
using Gygl.BLL.News.Service;
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Gygl.WebPage.Controllers
{
    public class NewsController : Controller
    {
        [Dependency]
        public INewsService NewsService { get; set; }

        [OutputCache(Duration = 120,VaryByParam ="count")]
        public async Task<JsonResult> GetNewsList(int count)
        {
            var result = await NewsService.getNewsList(101, count);
            return Json(result,JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Duration = 120, VaryByParam = "page")]
        public async Task<JsonResult> GetPagedNewsList(int page)
        {
            var result = await NewsService.getPagedNewsList(20, page);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetNews(int newsId)
        {
            var result = await NewsService.getNewsById(newsId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Duration = 120)]
        public PartialViewResult ReadNews()
        {
            return PartialView();
        }

        [OutputCache(Duration = 120)]
        public PartialViewResult NewsList()
        {
            return PartialView();
        }

        [OutputCache(Duration = 120)]
        public ActionResult Index()
        {
            return View();
        }

    }
}

Gygl.WebPage/Controllers/RegisterController.cs
using Gygl.BLL.Register.Manage;
using Gygl.BLL.Register.ViewModels;
using Gygl.BLL.Share;
using Microsoft.Practices.Unity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Gygl.WebPage.Controllers
{
    public class RegisterController : Controller
    {
       [Dependency]
        public IUserManage UserManage { get; set; }
        public ActionResult Login()
        {
            return View();
        }

        public async Task<JsonResult> JsonLogin(string u, string p, bool auto = false)
        {
            var result = await UserManage.Login(u, p, auto);
            return Json(result);
        }
        public async Task<JsonResult> JsonLoginCheck()
        {
            var result = await UserManage.LoginCheck();
            return Json(result);
        }
        public void JsonLoginOut()
        {
            UserManage.LoginOut();
        }
        public async Task<JsonResult> JsonForget(string u, string e)
        {
            var result = await UserManage.Forget(u, e);
            return Json(result);
        }
        public ActionResult Reg()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Reg(RegViewModel rvm)
        {
            if (ModelState.IsValid)
            {
                var a = await UserManage.Reg(rvm);
                if(a.Item1)
                    return View("SendEmail", rvm);
                else
                    return View("ErrorEmail", (object)a.Item2);
            }
            return View();
        }
        public async Task<ActionResult> Manage()
        {
            var result =await UserManage.GetUser();
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Manage(UserViewModel uvm)
        {
            if (ModelState.IsValid)
            {
                await UserManage.EditUser(uvm);
            }
            return View(uvm);
        }
        public ActionResult ForgetPassword()
        {
            return View();
        }
        public ActionResult SendEmail(RegViewModel uvm)
        {
            return View(uvm);
        }
        public ActionResult ErrorEmail(string a)
        {
            return View(a);
        }
        public async Task<ActionResult> Activate(int? uid, string code)
        {
            var a = await UserManage.Activate(uid.Value, code);
            return View(a);
        }

        public async Task<ActionResult> ChangePassword(int? uid, string code)
        {
            var a = await UserManage.GetUser(uid.Value, code);
            if (a == null)
            {
                return RedirectToAction("ForgetPassword");
            }
            else
            {
                return View(a);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(PasswordViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                return View("ChangePasswordSuccess", await UserManage.UpdatePass(pvm));
            }
            return View(pvm);
        }
        public ActionResult ChangePasswordSuccess(PasswordViewModel pvm)
        {
            return View(pvm);
        }
        public async Task<JsonResult> CkUserName(string username)
        {
            var result = await UserManage.CkUserName(username.Trim());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult LoginJump(Jump model)
        {
            return View(model);
        }
    }
}

Gygl.WebPage/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gygl.WebPage.Controllers
{
    public class StaticController : Controller
    {

        [OutputCache(Duration = 1200)]
        public ActionResult Order()
        {
            return View();
        }

        [OutputCache(Duration = 1200)]
        public ActionResult Introduction()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Faq()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Contact()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Notice()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Advertisement()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult EssayNotice()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Council()
        {
            return View();
        }
    }
}

Gygl.WebPage/Views/Home/Bottom.cshtml
<div id="q_top13">
    <div id="m_top013">
        <div class="blankleftbottom">
            <div class="blankbottom"><a href="@Url.Action("Council","Static")" target="_blank">理事单位</a>&nbsp; &nbsp;<a href="@Url.Action("Advertisement","Static")">广告合作</a>&nbsp; &nbsp;<a href="@Url.Action("Order","Static")">杂志订购</a>&nbsp; &nbsp;<a href="@Url.Action("Notice","Static")">投稿须知</a></div>
            <div>
                地址：上海市宝昌路297号&nbsp;邮编：325401<br />
                电话：（021）51020808转5117、5103、5117<br />
                传真：（021）51803255  Email:<a href="mailto:shgygl@126.com">shgygl@126.com</a>
            </div>
        </div>
        <div class="floatleft">
            <div class="bottomerwei"><img src="/Content/images/erwei.gif" width="83" height="83" /></div>
            <div class="bottombanquan">
                Copyright @@1985-2016 All Right Reserved. <br />
                版权所有 上海工业锅炉研究所<br />
                网络备案号:沪ICP备09086544号
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Home/Header.cshtml
<div id="q_top03">
    <div id="m_top03">
        <!--大图切换-->
    </div>
</div>
<div id="q_top04">
    <div id="m_top04">
        <div id="top04">
            <div><img src="/Content/images/magazine_top05.gif" width="15" height="15" /><a href="/Magazine">在线阅读</a></div>
            <div><img src="/Content/images/magazine_top05.gif" width="15" height="15" /><a href="@Url.Action("Order","Static")">杂志订购</a></div>
            @*<div><img src="/Content/images/magazine_top05.gif" width="15" height="15" /><a href="#">期刊下载（pdf版）</a></div>*@
        </div>
    </div>
</div>

Gygl.WebPage/Views/Home/Index.cshtml
@{
    ViewBag.Title = "首页";
}
@section Css{
    @Styles.Render("~/Content/homecss")
}
@section scripts{
    @Scripts.Render("~/bundles/home")
}
@section hscripts{
    @Scripts.Render("~/bundles/angular")
}
@section Header{
    @Html.Action("Header", "Home")
}
<div id="q_top05">
    <div id="q_top05_02">
        <div id="m_top05">
            <div id="top05_title">
                <img src="/Content/images/magazine01.png" width="156" height="78" />
            </div>
            <div id="top05_news" ng-controller="news">
                <ul>
                    <li ng-repeat="n in nl">
                        <a ng-href="/News#/ReadNews/{{n.ID}}">{{n.Title}}</a>&nbsp;<span class="sj">{{n.RegDate|jsonDate:'yyyy-MM-dd'}}</span>
                    </li>
                </ul>
                <div class="top05_newsmore"><a ng-href="/News#/NewsList/1">more...</a></div>
            </div>
        </div>
    </div>
</div>
<div id="q_top06">
    <div id="q_top06_02">
        <div id="m_top06">
            <div class="tcenter ttitle"><img src="/Content/images/magazine02.png" width="145" height="37" /></div>
            @*<div id="magazine_search">
                <div><input type="search" value="请输入文章名" class="searchbox" onfocus="this.value=''" onblur="if(this.value==''){this.value='请输入文章名'}"></div>
                <div>
                    <select class="searchbox02">
                        <option>年份选择</option>
                        <option>2010年</option>
                        <option>2011年</option>
                    </select>
                </div>
                <div>
                    <select class="searchbox02">
                        <option>期数选择</option>
                        <option>第1期</option>
                        <option>第2期</option>
                        <option>第3期</option>
                        <option>第4期</option>
                        <option>第5期</option>
                        <option>第6期</option>
                    </select>
                </div>
                <div><img src="/Content/images/magazinebutton01.gif" width="68" height="34" /></div>
            </div>*@
            <div class="shengming01"><img src="/Content/images/magazine03.png" width="342" height="33" /></div>
            <div ng-controller="current">
                <div class="newstitle02">{{cp.Year}}年第&nbsp;<span class="qishufont">{{cp.Period}}</span>&nbsp;期</div>
                <div id="newsabc">
                    <ul>
                        <li ng-repeat="title in cp.Title">
                        <span class="qishuliepretit">[{{title.Category}}]</span>&nbsp;<a href="/Magazine/#/Periodical/{{title.GyglID}}/{{title.Url}}">{{title.Title|limitTo:20}}...{{title.Author|limitTo:11}}</a>
                        </li>
                    </ul>
                    <div class="magazinebutton02"><a href="/Magazine/#/GetPeriod/{{cp.ID}}"><img src="/Content/images/magazinebutton02.gif" width="120" height="42" /></a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="q_top07">
    <div id="m_top07">
        <div class="bottomblank35">
            <p>
                《工业锅炉》杂志是经原国家科委批准，由上海工业锅炉研究所主办的以介绍(工业)锅炉行业新技术、新经验为主的综合性技术刊物。《工业锅炉》为双月刊、大16开彩色印刷，国内外公开发行。
                报道内容包括有关锅炉的设计、制造、工艺、标准、辅机、环保技术、水处理、节能改造、运行管理、事故分析、司炉工园地、行业动态等，选稿注重创新性和实用性。本刊系中国科技论文统计源期刊（中国科技核心期刊），中国科学引文数据库来源期刊，入选中国学术期刊（光盘版），并获全国能
                源刊物优秀期刊奖。
            </p>
        </div>
        <div id="magazinejies">
            <div><img src="/Content/images/lie01.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie02.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie03.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie04.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie05.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie06.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie07.gif" width="75" height="167" /></div>
            <div><img src="/Content/images/lie08.gif" width="75" height="167" /></div>
        </div>
        <div id="magazinedg">
            <div class="magazinedglefgblank"><a href="@Url.Action("Order","Static")" target="_blank"><img src="/Content/images/magazinebutton03.gif" width="120" height="41" /></a></div>
            <div><img src="/Content/images/magazine02.gif" width="130" height="41" /></div>
        </div>
    </div>
</div>
<div id="q_top07_bottom">
    <div id="q_top07_02_bottom">
    </div>
</div>
<div id="q_top08">
</div>
<div id="q_top09">
    <div id="m_top09">
        <div class="textaligncenter"><img src="/Content/images/magazinezhengaotit.gif" width="131" height="34" /></div>
        <div id="shengaosan">
            <div>
                <div><a href="http://139.224.30.88/journalx_gygl/authorLogOn.action" target="_blank"><img src="/Content/images/shengao01_1.gif" width="147" height="147" /></a></div>
                <div><img src="/Content/images/magazineonline.gif" width="80" height="23" /></div>
            </div>
            <div>
                <div><img src="/Content/images/shengao02_1.gif" width="147" height="147" /></div>
                <div><img src="/Content/images/magazinecha.gif" width="119" height="23" /></div>
            </div>
            <div>
                <div><img src="/Content/images/shengao03_1.gif" width="147" height="147" /></div>
                <div><img src="/Content/images/magazinezhengaolu.gif" width="119" height="23" /></div>
            </div>
        </div>
        <div><img src="/Content/images/magazine05.png" width="361" height="75" /></div>
        <div class="textalignright"><img src="/Content/images/magazine06.png" width="268" height="45" /></div>
    </div>
</div>
<div id="q_top10">
    <div id="q_top10_02">
    </div>
</div>
<div id="q_top11">
    <div id="q_top11_02">
        <div id="m_top011">
            <div>
                <div>
                    <div><img src="/Content/images/magazine07.gif" width="134" height="377" /></div>
                    <div>
                        2008年迁址<br />
                        上海宝昌路297号
                    </div>
                </div>
                <div>
                    <div>
                        《工业锅炉》<br />
                        优秀论文评选活动
                    </div>
                    <div><img src="/Content/images/magazine08.gif" width="134" height="377" /></div>
                </div>
                <div>
                    <div><img src="/Content/images/magazine09.gif" width="134" height="377" /></div>
                    <div>
                        《工业锅炉》杂志<br />
                        1985年创刊
                    </div>
                </div>
                <div>
                    <div>
                        《工业杂志》<br />
                        广告&理事单位
                    </div>
                    <div><img src="/Content/images/magazine10.gif" width="134" height="377" /></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="q_top12">
    <div id="q_top12_02">
    </div>
</div>

Gygl.WebPage/Views/Home/Top.cshtml
<div id="q_top01">
    <div id="m_top01">
        <div class="top01_01"><img src="/Content/images/magazine_top01.gif" width="19" height="13" />投稿邮箱：<a href="mailto:shgygl@126.com">shgygl@126.com</a></div>
        <div class="top01_02"><img src="/Content/images/magazine_top02.gif" width="17" height="17" />电话：021-51020808转5103、5115、5117</div>
        @*<div id="zudltc">
            <div class="top01_04" id="yctc"><a href="@Url.Action("Login","Register")">登录&nbsp;<img src="/Content/images/magazine_top04.gif" width="5" height="6" /></a></div>
            <div id="yctc01" style="display:none">
                <div id="tip" class="top01_03_02"></div>
                <div class="top01_04" id="loginout"><a href="#">退出</a></div>
            </div>
            <div class="top01_03" id="reg"><img src="/Content/images/magazine_top03.gif" width="19" height="19" /><a href="@Url.Action("Reg","Register")">免费注册</a></div>
            <div class="top01_03" id="usermanage" style="display:none"><img src="/Content/images/magazine_top03.gif" width="19" height="19" /><a href="@Url.Action("Manage","Register")">账号管理</a></div>
        </div>*@
    </div>
</div>

Gygl.WebPage/Views/Home/Top2.cshtml
<div id="q_top02chong">
    <div id="m_top02chong">
        <div id="chong01_01"><img src="/Content/images/magazine_top02_logo.gif" width="205" height="68" /></div>
        @Html.Action("TopShare")
    </div>
</div>
<div id="q_top02bg" style="display: none;"></div>

Gygl.WebPage/Views/Home/Top3.cshtml
<div id="q_top02chong" class="qtopchongtop">
    <div id="m_top02chong">
        <div id="chong01_01"><img src="/Content/images/magazine_top02_logo.gif" width="205" height="78" /></div>
        @Html.Action("TopShare")
    </div>
</div>
<div id="q_top02bg_2" style="display: none;"></div>

Gygl.WebPage/Views/Home/TopShare.cshtml
<div id="ietuchong01_02">
    <div>
        <a href="/"><img src="/Content/images/magadh01_1.gif" width="44" height="68" /></a>
        <ul>
            <li><a href="@Url.Action("Index","News")">最新动态</a></li>
            <li><a href="@Url.Action("Introduction","Static")">期刊介绍</a></li>
        </ul>
    </div>
    <div>
        <a href="/Magazine">
            <img src="/Content/images/magadh02_1.gif" width="101" height="68" />
        </a>
        <ul>
            <li><a href="/Magazine#/GetPeriod">最新一期</a></li>
            <li><a href="/Magazine">全部期刊</a></li>
            <li><a href="/Magazine#/SelectYear?year=@DateTime.Now.Year">本年度期刊</a></li>
        </ul>
    </div>
    <div>
       <img src="/Content/images/magadh03_1.gif" width="70" height="68" />
        <ul class="m_top02ul03">
            <li><a href="@Url.Action("EssayNotice","Static")">征文通知</a></li>
            <li><a href="@Url.Action("Notice","Static")">投稿须知</a></li>
            <li><a href="@Url.Action("Faq","Static")">常见问题</a></li>
            <li><a href="@Url.Action("Contact","Static")">联系我们</a></li>
        </ul>
    </div>
    <div>
        <a href="http://139.224.30.88/journalx_gygl" target="_blank">
            <img src="/Content/images/magadh04_1.gif" width="91" height="68" />
        </a>
            <ul>
                <li><a href="http://139.224.30.88/journalx_gygl/authorLogOn.action" target="_blank">作者中心</a></li>
                <li><a href="http://139.224.30.88/journalx_gygl/expertLogOn.action" target="_blank">专家中心</a></li>
                <li><a href="http://139.224.30.88/journalx_gygl/editorCommitteeLogOn.action" target="_blank">编委中心</a></li>
                <li><a href="http://139.224.30.88/journalx_gygl/editorInChiefLogOn.action" target="_blank">主编中心</a></li>
                <li><a href="http://139.224.30.88/journalx_gygl/editorLogOn.action" target="_blank">编辑中心</a></li>
            </ul>
</div>
    <div>
        <img src="/Content/images/magadh05_1.gif" width="118" height="68" />
        <ul>
            <li><a href="#">优秀论文评选</a></li>
            <li><a href="#">历年评选结果</a></li>
        </ul>
    </div>
    <div>
        <img src="/Content/images/magadh06_1.gif" width="97" height="68" />
        <ul class="m_top02ul06">
            <li><a href="@Url.Action("Advertisement","Static")">杂志广告</a></li>
            <li><a href="@Url.Action("Council","Static")">杂志理事会</a></li>
        </ul>
    </div>
</div>