Gygl.WebPage/Controllers/MagazineController.cs
using Gygl.BLL.Magazine.Service;
using Microsoft.Practices.Unity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Gygl.WebPage.Controllers
{
    public class MagazineController : Controller
    {
        [Dependency]
        public IGyglCategoryService GyglCategoryService { get; set; }

        [Dependency]
        public IGyglService GyglService { get; set; }

        [Dependency]
        public IArticleService ArticleService { get; set; }

        [Dependency]
        public ICategoryService CategoryService { get; set; }

        [Dependency]
        public ICommentService CommentService { get; set; }

        [OutputCache(Duration = 120)]
        public PartialViewResult Catalog()
        {
            //return PartialView(GyglCategoryService.getCatalogByID(id));
            return PartialView();
        }

        public async Task<JsonResult> GetCatalog(int id)
        {
            var result = await GyglCategoryService.getCatalogByID(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Duration = 120)]
        public PartialViewResult RightNav()
        {
            return PartialView();
        }


        [OutputCache(Duration = 120)]
        public PartialViewResult Periodical()
        {
            //var ret = GyglService.getPeriodicalById(id);
            //if (ret != null)
            //    return PartialView(GyglService.getPeriodicalById(id));
            //else
            //    return null;
            return PartialView();
        }

        [OutputCache(Duration = 120, VaryByParam = "id")]
        public async Task<JsonResult> GetPeriod(int id)
        {
            var result = await GyglService.getPeriod(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetIp()
        {
            var result = Task.Run(() =>
            {
                return
                HttpContext.Request.UserHostAddress;
            });
            return Json(await result, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> getComment(int aid, int page)
        {
            var result = await CommentService.getCommentByArticle(aid, 3, page);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task smtComment(int aid, string message)
        {
            if (message.Trim() != string.Empty && message != null)
                await CommentService.smtComment(aid, message);
        }


        [OutputCache(Duration = 120)]
        public PartialViewResult SelectYear()
        {
            return PartialView();
        }
        /// <summary>
        /// 页面内获取
        /// </summary>
        /// <param name="year"></param>
        /// <param name="period"></param>
        /// <param name="page"></param>
        /// <returns>改造</returns>
        public async Task<JsonResult> getSelectYear(int? year, int? period, int page)
        {
            var result = await GyglService.getPeriodicalByYear(year, period, 6, page);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Duration = 120)]
        public PartialViewResult SelectArticle()
        {
            return PartialView();
        }
        /// <summary>
        /// 文章分页
        /// </summary>
        /// <param name="year"></param>
        /// <param name="period"></param>
        /// <param name="category"></param>
        /// <param name="page"></param>
        /// <returns>改造</returns>
        public async Task<JsonResult> getSelectArticle(int? year, int? period, int? category, string key, int page)
        {
            var result = await ArticleService.getArticleByCategory(year, period, category, key, 20, page);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //public PartialViewResult SelectPeriod(int year, int period)
        //{
        //    var ret = GyglService.getPeriodBySearch(year, period);
        //    if (ret != null)
        //        return PartialView("CopyRight", ret);
        //    return null;
        //}
        public async Task<JsonResult> GetSelectPeriod(int year, int period)
        {
            var result = await GyglService.getPeriodBySearch(year, period);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 版权页CopyRight
        /// </summary>
        /// <param name="year"></param>
        /// <returns></returns>
        [OutputCache(Duration = 120)]
        public PartialViewResult CopyRight()
        {
            //return PartialView(GyglService.getPeriodicalById(id));
            return PartialView();
        }
        [OutputCache(Duration = 120, VaryByParam = "id")]
        public async Task<JsonResult> GetCopyRight(int? id)
        {
            var result = await GyglService.getPeriodicalById(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// 理事会
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [OutputCache(Duration = 120)]
        public PartialViewResult Council()
        {
            return PartialView();
        }
        //用版权页获取
        //public async Task<JsonResult> GetCouncil(int? id)
        //{
        //    var result = await GyglService.getPeriodicalById(id);
        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}

        [OutputCache(Duration = 120, VaryByParam = "aid")]
        public async Task<JsonResult> GetPages(int aid)
        {
            //await ArticleService.updateHit(aid);//有问题
            var result = await ArticleService.getPages(aid);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 120, VaryByParam = "pid")]
        //public async Task<JsonResult> GetArticleList(int pid)
        //{
        //    var result = await ArticleService.getArticleList(pid);
        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}

        [OutputCache(Duration = 120, VaryByParam = "pid")]
        public async Task<JsonResult> GetFirstPages(int pid)
        {
            var result = await ArticleService.getFirstPages(pid);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetCategoryList(int y, int p)
        {
            var result = await GyglCategoryService.getSearchCatalog(y, p);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Duration = 120)]
        public async Task<JsonResult> GetDefaultCategoryList()
        {
            var result = await CategoryService.getCategoryList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        //首页的10条栏目
        [OutputCache(Duration = 120)]
        public async Task<JsonResult> GetCurrentPeriod()
        {
            var result = await GyglService.getCurrentPeriod();
            return Json(result,JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Duration = 120)]
        public PartialViewResult Search()
        {
            return PartialView();
        }

        [OutputCache(Duration = 120)]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Gygl.WebPage/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gygl.WebPage.Controllers
{
    public class StaticController : Controller
    {

        [OutputCache(Duration = 1200)]
        public ActionResult Order()
        {
            return View();
        }

        [OutputCache(Duration = 1200)]
        public ActionResult Introduction()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Faq()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Contact()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Notice()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Advertisement()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult EssayNotice()
        {
            return View();
        }
        [OutputCache(Duration = 1200)]
        public ActionResult Council()
        {
            return View();
        }
    }
}

Gygl.WebPage/Views/Magazine/Catalog.cshtml
<div id="q_topml">
    <div id="muread" show-catalog>目录</div>
    <div id="msgDiv">
        <div id="muludetail">
            <div class="subNav readmulutit"><img src="/Content/images/readgygl.gif" width="122" height="26" /></div>
            <div class="readmululine"></div>
                <div class="subNavtit" ng-repeat="item in catalog">
                    <span class="icon-list readleftli"></span>&nbsp;<a href="javascript:void(0)" class="subNav" show-sub>{{item.Category}}</a>
                    <ul>
                            <li ng-repeat="subItem in item.Title"><span class="icon-caret-right">&nbsp;</span><a href="javascript:void(0)" ng-click="click(subItem.Url)">{{subItem.Title}}</a></li>
                    </ul>
                </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/CopyRight.cshtml
<div id="q_top05">
    <div id="m_top05">
        <div id="top05">
            <div class="top05_01" id="readbq">
                <div class="blank30"></div>
                <div id="readfeng">
                    <div class="readfengzuo">
                        <div><img ng-src="/Content/Upload/Magazine/Cover/{{cr.CoverImage}}" width="236" height="320" /></div>
                        <div class="readdg blanktop20">
                            <div class="readingbtn blankleft30 "><a ng-href="#/GetPeriod/{{cr.Up}}">上一期</a></div><div>&nbsp; </div><div class="readingbtn"><a ng-href="#/GetPeriod/{{cr.Down}}">下一期</a></div>
                        </div>
                    </div>
                    <div class="readfengyou">
                        <div class="readqishuyou">
                            <div class="blanktop20"><span class="readtitqishu">{{cr.Year}}年第 {{cr.Period}} 期</span></div>
                            <div class="blank20"></div>
                            <div id="readqishuyouchai">
                                <div class="readqishuyouchai_left">
                                    <span class="readlan">出版日期：</span>{{cr.Publish}}<br />
                                    <span class="readlan">周&nbsp; &nbsp; 期：</span>双月刊(总第 {{cr.TotalPeriod}} 期)<br />
                                    <span class="readlan">主办单位：</span>上海工业锅炉研究所<br />
                                    <span class="readlan">ISSN：</span>1004-8774<br />
                                    <span class="readlan"> 广告经营许可证：</span>3100820110002号<br />
                                    <span class="readlan"> 定&nbsp; &nbsp; 价：</span><span class="readdj">18元/期</span>
                                </div>
                                <div>
                                    <span class="readlan">开&nbsp; &nbsp; 本：</span>16开<br />
                                    <span class="readlan">CN：</span>31-1400/TK<br />
                                    <span class="readlan">邮发代号：</span>4-586<br />
                                </div>
                            </div>
                        </div>
                        <div class="blank20"></div>
                        <div class="readjj lineheight01"><span class="readlan lineheight01">简介：</span><a href="javascript:void(0)">《工业锅炉》杂志是经原国家科委批准，由上海工业锅炉研究所主办的以介绍(工业)锅炉行业新技术、新经验为主的综合性技术刊物。《业锅炉》为双月刊、大16开彩色印刷，国内外公开发行。报道内容包括有关...</a></div>
                        <div class="blank10"></div>
                        <div class="readdg readdgyou blanktop20">
                            <div class="readbtn readbtndg"><a href="@Url.Action("Order","Static")">订&nbsp; 购</a></div>
                            <div class="readbtn readbtnyd"><a href="#/Periodical/{{cr.ID}}">在线阅读</a></div>
                            @*<div class="readbtn readbtnxz"><a href="#">下载本期</a></div>*@
                        </div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="readbglan">
                    <span class="icon-star">&nbsp;</span>中国科技论文统计源期刊（中国科技核心期刊）<br />
                    <span class="icon-star">&nbsp;</span>中国科学引文数据库来源期刊<br />
                    <span class="icon-star">&nbsp;</span>中国期刊网、中国学术期刊（光盘版）全文记录期刊<br />
                    <span class="icon-star">&nbsp;</span>全国能源刊物优秀期刊<br />
                    <span class="icon-star">&nbsp;</span>中国学术期刊综合评论数据库来源期刊<br />
                </div>
                <div class="mingyuzhubian">
                    <article ng-bind-html="cr.CopyRight|trustHtml"></article>
                </div>
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/Council.cshtml
<div id="q_top05">
    <div id="m_top05">
        <div id="top05">
            <div class="top05_01" id="readbq">
                <div class="blank30"></div>
                <div id="readfeng">
                    <div class="readfengzuo">
                        <div><img ng-src="/Content/Upload/Magazine/Cover/{{cr.CoverImage}}" width="236" height="320" /></div>
                        <div class="readdg blanktop20">
                            <div class="readingbtn blankleft30 "><a ng-href="#/GetPeriod2/{{cr.Up}}">上一期</a></div><div>&nbsp; </div><div class="readingbtn"><a ng-href="#/GetPeriod2/{{cr.Down}}">下一期</a></div>
                        </div>
                    </div>
                    <div class="readfengyou">
                        <div class="readqishuyou">
                            <div class="blanktop20"><span class="readtitqishu">{{cr.Year}} 年第 {{cr.Period}} 期</span></div>
                            <div class="blank20"></div>
                            <div id="readqishuyouchai">
                                <div class="readqishuyouchai_left">
                                    <span class="readlan">出版日期：</span>{{cr.Publish}}<br />
                                    <span class="readlan">周&nbsp; &nbsp; 期：</span>双月刊(总第 {{cr.TotalPeriod}} 期)<br />
                                    <span class="readlan">主办单位：</span>上海工业锅炉研究所<br />
                                    <span class="readlan">ISSN：</span>1004-8774<br />
                                    <span class="readlan"> 广告经营许可证：</span>3100820110002号<br />
                                    <span class="readlan"> 定&nbsp; &nbsp; 价：</span><span class="readdj">18元/期</span>
                                </div>
                                <div>
                                    <span class="readlan">开&nbsp; &nbsp; 本：</span>16开<br />
                                    <span class="readlan">CN：</span>31-1400/TK<br />
                                    <span class="readlan">邮发代号：</span>4-586<br />
                                </div>
                            </div>
                        </div>
                        <div class="blank20"></div>
                        <div class="readjj lineheight01"><span class="readlan lineheight01">简介：</span><a href="javascript:void(0)">《工业锅炉》杂志是经原国家科委批准，由上海工业锅炉研究所主办的以介绍(工业)锅炉行业新技术、新经验为主的综合性技术刊物。《业锅炉》为双月刊、大16开彩色印刷，国内外公开发行。内容..</a></div>
                        <div class="blank10"></div>
                        <div class="readdg readdgyou blanktop20">
                            <div class="readbtn readbtndg"><a href="@Url.Action("Order","Static")">订&nbsp; 购</a></div>
                            <div class="readbtn readbtnyd"><a href="#/Periodical/{{cr.ID}}">在线阅读</a></div>
                            @*<div class="readbtn readbtnxz"><a href="#">下载本期</a></div>*@
                        </div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="blank30"></div>
                <div id="lsh">《工业锅炉》杂志理事会</div>
                <div class="mingyuzhubian01">
                    <article ng-bind-html="cr.Council|trustHtml"></article>
                </div>
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/GetPeriod.cshtml
@model Gygl.BLL.Magazine.ViewModels.GyglViewModel
<div id="q_top05">
    <div id="m_top05">
        <div id="top05">
            <div class="top05_01" id="readbq">
                <div class="blank30"></div>
                <div id="readfeng">
                    <div class="readfengzuo">
                        <div><img src="/Content/Upload/Magazine/Cover/@Model.CoverImage" width="236" height="320" /></div>
                        <div class="readdg blanktop20">
                            <div class="readingbtn blankleft30 "><a href="#/GetPeriod/@Model.Up">上一期</a></div><div>&nbsp; </div><div class="readingbtn"><a href="#/GetPeriod/@Model.Down">下一期</a></div>
                        </div>
                    </div>
                    <div class="readfengyou">
                        <div class="readqishuyou">
                            <div class="blanktop20"><span class="readtitqishu">@Model.Year 年第 @Model.Period 期</span></div>
                            <div class="blank20"></div>
                            <div id="readqishuyouchai">
                                <div class="readqishuyouchai_left">
                                    <span class="readlan">出版日期：</span>@Model.Publish<br />
                                    <span class="readlan">周&nbsp; &nbsp; 期：</span>双月刊(总第 @Model.TotalPeriod 期)<br />
                                    <span class="readlan">主办单位：</span>上海工业锅炉研究所<br />
                                    <span class="readlan">ISSN：</span>1004-8774<br />
                                    <span class="readlan"> 广告经营许可证：</span>3100820110002号<br />
                                    <span class="readlan"> 定&nbsp; &nbsp; 价：</span><span class="readdj">18元/期</span>
                                </div>
                                <div>
                                    <span class="readlan">开&nbsp; &nbsp; 本：</span>16开<br />
                                    <span class="readlan">CN：</span>31-1400/TK<br />
                                    <span class="readlan">邮发代号：</span>4-586<br />
                                </div>
                            </div>
                        </div>
                        <div class="blank20"></div>
                        <div class="readjj lineheight01"><span class="readlan lineheight01">简介：</span><a href="javascript:void(0)">《工业锅炉》杂志是经原国家科委批准，由上海工业锅炉研究所主办的以介绍(工业)锅炉行业新技术、新经验为主的综合性技术刊物。《业锅炉》为双月刊、大16开彩色印刷，国内外公开发行。报道内容包括有关...</a></div>
                        <div class="blank10"></div>
                        <div class="readdg readdgyou blanktop20">
                            <div class="readbtn readbtndg"><a href="@Url.Action("Order","Static")">订&nbsp; 购</a></div>
                            <div class="readbtn readbtnyd"><a href="#/Periodical/@Model.ID">在线阅读</a></div>
                            @*<div class="readbtn readbtnxz"><a href="#">下载本期</a></div>*@
                        </div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="readbglan">
                    <span class="icon-star">&nbsp;</span>中国科技论文统计源期刊（中国科技核心期刊）<br />
                    <span class="icon-star">&nbsp;</span>中国科学引文数据库来源期刊<br />
                    <span class="icon-star">&nbsp;</span>中国期刊网、中国学术期刊（光盘版）全文记录期刊<br />
                    <span class="icon-star">&nbsp;</span>全国能源刊物优秀期刊<br />
                    <span class="icon-star">&nbsp;</span>中国学术期刊综合评论数据库来源期刊<br />
                </div>
                <div class="mingyuzhubian">
                    @Html.Raw(Model.CopyRight)
                </div>
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/GetPeriod2.cshtml
@model Gygl.BLL.Magazine.ViewModels.GyglViewModel
<div id="q_top05">
    <div id="m_top05">
        <div id="top05">
            <div class="top05_01" id="readbq">
                <div class="blank30"></div>
                <div id="readfeng">
                    <div class="readfengzuo">
                        <div><img src="/Content/Upload/Magazine/Cover/@Model.CoverImage" width="236" height="320" /></div>
                        <div class="readdg blanktop20">
                            <div class="readingbtn blankleft30 "><a href="#/GetPeriod2/@Model.Up">上一期</a></div><div>&nbsp; </div><div class="readingbtn"><a href="#/GetPeriod2/@Model.Down">下一期</a></div>
                        </div>
                    </div>
                    <div class="readfengyou">
                        <div class="readqishuyou">
                            <div class="blanktop20"><span class="readtitqishu">@Model.Year 年第 @Model.Period 期</span></div>
                            <div class="blank20"></div>
                            <div id="readqishuyouchai">
                                <div class="readqishuyouchai_left">
                                    <span class="readlan">出版日期：</span>@Model.Publish<br />
                                    <span class="readlan">周&nbsp; &nbsp; 期：</span>双月刊(总第 @Model.TotalPeriod 期)<br />
                                    <span class="readlan">主办单位：</span>上海工业锅炉研究所<br />
                                    <span class="readlan">ISSN：</span>1004-8774<br />
                                    <span class="readlan"> 广告经营许可证：</span>3100820110002号<br />
                                    <span class="readlan"> 定&nbsp; &nbsp; 价：</span><span class="readdj">18元/期</span>
                                </div>
                                <div>
                                    <span class="readlan">开&nbsp; &nbsp; 本：</span>16开<br />
                                    <span class="readlan">CN：</span>31-1400/TK<br />
                                    <span class="readlan">邮发代号：</span>4-586<br />
                                </div>
                            </div>
                        </div>
                        <div class="blank20"></div>
                        <div class="readjj lineheight01"><span class="readlan lineheight01">简介：</span><a href="javascript:void(0)">《工业锅炉》杂志是经原国家科委批准，由上海工业锅炉研究所主办的以介绍(工业)锅炉行业新技术、新经验为主的综合性技术刊物。《业锅炉》为双月刊、大16开彩色印刷，国内外公开发行。内容..</a></div>
                        <div class="blank10"></div>
                        <div class="readdg readdgyou blanktop20">
                            <div class="readbtn readbtndg"><a href="@Url.Action("Order","Static")">订&nbsp; 购</a></div>
                            <div class="readbtn readbtnyd"><a href="#/Periodical/@Model.ID">在线阅读</a></div>
                            @*<div class="readbtn readbtnxz"><a href="#">下载本期</a></div>*@
                        </div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="blank30"></div>
                <div id="lsh">《工业锅炉》杂志理事会</div>
                <div class="mingyuzhubian01">
                    @Html.Raw(Model.Council)
                </div>
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
    ViewBag.Title = "期刊阅读";
}
@section hscripts{
    @Scripts.Render("~/bundles/angular")
}
<div ng-view></div>

Gygl.WebPage/Views/Magazine/Periodical.cshtml
<div>
    <div id="q_top004">
        <div id="m_top004">
            <div id="top004">
                <div><img src="/Content/images/readonline.gif" width="184" height="38" /></div>
                <div class="readqishu">{{period.Year}} 年第&nbsp;<span class="readqishu02">{{period.Period}}</span>&nbsp; 期（总第 {{period.TotalPeriod}} 期）</div>
                <div class="readlsbq">
                    <div class="readlsh"><a ng-href="#/GetPeriod2/{{period.ID}}">理事会</a></div>
                    <div class="readbqy"><a ng-href="#/GetPeriod/{{period.ID}}">版权页</a></div>
                </div>
            </div>
        </div>
    </div>
 @Html.Action("Catalog", "Magazine")
    <div id="q_top05">
        <div id="m_top05">
            <div id="top05">
                <div class="top05_01" close-menu>
                    <div ng-repeat="page in pages" ng-init="pUrl=page.Url">
                        <img ng-if="pUrl==''||pUrl==null" ng-src="~/Content/Upload/Magazine/{{page.Location}}/{{page.ImageID}}" />
                        <a ng-if="pUrl!=''&&pUrl!=null" href="javascript:void(0)" ng-click="loc(page.Url)"><img ng-src="~/Content/Upload/Magazine/{{page.Location}}/{{page.ImageID}}" /></a>
                    </div>
                </div>
                @Html.Action("RightNav", "Magazine")
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/SelectArticle.cshtml
<div id="q_top05">
    <div id="m_top05">
        <div id="top05">
            <div class="top05_01" id="readbq">
                <div class="blank30"></div>
                <div id="lsh">《工业锅炉》——{{category}}</div>
                <div class="mingyuzhubian01 readlanmulie" id="conreadlie">
                        <ul ng-repeat="article in articles">
                            <li class="readlan">{{article.Year}}年第{{article.Period}}期</li>
                            <li class="readlantit"><a ng-href="#/Periodical/{{article.GyglID}}/{{article.Url}}" title="{{article.Category}}:{{article.Title}}">{{article.Title|limitTo : 27}}</a></li>
                            <li class="readlanzz">{{article.Author|limitTo : 10}}</li>
                        </ul>
                     <div class="blank30"></div>
                    <div class="readlanmulieline"></div>
                    <div class="pagination">
                        <ul id="pagingdata"></ul>
                    </div>
                    <div style="clear:both"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Gygl.WebPage/Views/Magazine/SelectYear.cshtml
<div id="q_top005_1">
    <div id="m_top005_1">
        <div id="top005_1">
            <div class="top05_01_02" id="readbq">
                <div class="blank30"></div>
                <div id="readfeng">
                    <div class="readfengyou02">
                        <div class="readqishuyou02">
                            <div class="blanktop20"><span class="readtitqishu">《工业锅炉》杂志介绍</span>（双月刊）</div>
                            <div class="blank20"></div>
                            <div class="readjj lineheight01">
                                <p>
                                    《工业锅炉》杂志是经原国家科委批准，由上海工业锅炉研究所主办的以介绍(工业)锅炉行业新技术、新经验为主的综合性技术刊物。《工业锅炉》为双月刊、大16开彩色印刷，国内外公开发行。报道内容包括有关锅炉的设计、制造、工艺、标准、辅机、环保技术、水处理、节能改造、运行管理、事故分析、司炉工园地、行业动态等，选稿注重创新性和实用性。本刊系中国科技论文统计源期刊（中国科技核心期刊），中国科学引文数据库来源期刊，入选中国学术期刊（光盘版），并获全国能源刊物优秀。
                                </p>
                            </div>
                        </div>
                        <div id="readqishuyouchai02">
                            <span class="readlan">开&nbsp; &nbsp; 本：</span>16开<br />
                            <span class="readlan">主办单位：</span>上海工业锅炉研究所<br />
                            <span class="readlan"> 广告经营许可证：</span>3100820110002号<br />
                            <span class="readlan">I&nbsp;S&nbsp;S&nbsp;N：</span>1004-9774<br />
                            <span class="readlan">C&nbsp; &nbsp; &nbsp;N：</span>31-1400/TK<br />
                            <span class="readlan"> 定&nbsp; &nbsp; 价：</span><span class="readdj">18元/期</span><br />
                            <span class="readlan">邮发代号：</span>4-586
                            <div class="readdg readdgyou blanktop20">
                                <div class="readbtn readbtndg"><a href="@Url.Action("Order","Static")">订&nbsp; 购</a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="blank30"></div>
                <div class="bgcolor01">
                    <div class="bgcolor0202"></div>
                </div>
                <div class="top05_01">
                    <div class="blank30"></div>
                    <div id="readfeng" class="readfengnian">

                        <div class="readfengzuonianfen textcenter" ng-repeat="period in periods">
                            <div><a ng-href="#/GetPeriod/{{period.ID}}"><img ng-src="/Content/Upload/Magazine/Cover/{{period.CoverImage}}" width="189" height="256" /></a></div>
                            <div>
                                <div class="textcenter">{{period.Year}}年第 {{period.Period}} 期</div>
                                <div class="readdg">
                                    <div class="textcenter width100"><div class="readbtnnianfen readbtnxz"><a ng-href="#/GetPeriod/{{period.ID}}">阅读本期</a></div></div>
                                </div>
                            </div>
                        </div>
                        <div style="clear:both"></div>
                    </div>
                    <div class="blank30"></div>
                    <div class="readlanmulieline"></div>
                    <div class="pagination">
                        <ul id="pagingdata"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>